[package]
name = "babalang"
version = "1.1.2"
authors = ["RocketRace <neverquitben@gmail.com>"]
edition = "2018"
repository = "https://github.com/rocketrace/babalang/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "^0.7"